### ISSUE TITLE
why i cant add below object?

### ISSUE THREAD

**Issue by RezaErfani67** [PaquitoSoft/memored#12]
{

        DefaultFlow: require('./shared/defaultFlow/defaultFlow'),
        DefaultFlowChild: require('./shared/defaultFlow/defaultFlowChild'),
        User: require('./auth/user'),
        Task: require('./shared/Task/task'),
        Process: require('./shared/Task/process'),
        Workflow: require('./shared/Task/workflow'),
        Message: require('./shared/Message/message'),
        Mail: require('./official/mail/mail'),
        Fat: require('./technical/panel/fat'),
  
   
}

**Comment by PaquitoSoft** [comment]
I'm sorry but I don't understand the relation of this issue with this project.

**Comment by RezaErfani67** [comment]
i want to save this object in my cluster... but nothing result

**Comment by PaquitoSoft** [comment]
Could you provide more info about your problem?
What are all those require statements resolve to?
Bear in mind that you're trying to store something in a distributed cache system that rquires all cached values are serializable.
If you're trying to store functions, I'm not sure I understand what you're trying to accomplish.

**Comment by RezaErfani67** [comment]
I want to save all mongoose model in a memory to use it every where...
in my program user make mongodb collection and i want save his model on memory that every core of cpu can use it...

**Comment by PaquitoSoft** [comment]
You're not supposed to store a Mongoose model into any cache system. If you want to store an instance of that model (the result of a query, for instance) you should serialize that instance (or instances) to a plain object (for example) and store that serialized object.

Remember that _require_ acts as a singleton and only one instance of a required dependency is used in a nodejs process. It doesn't make sense to cache something that only exists once.

**Comment by RezaErfani67** [comment]
how can i serialize it?
```javascript
{
DefaultFlow: ƒ model(doc, fields, skipId)
$__insertMany: ƒ ()
$appliedHooks: true
$appliedMethods: true
$caught: true
$init: Promise {<resolved>: ƒ}
Query: ƒ ()
base: Mongoose {connections: Array(1), models: {…}, modelSchemas: {…}, options: {…}, _pluralize: ƒ, …}
collection: NativeCollection {collection: null, Promise: ƒ, opts: {…}, name: "defaultFlow", collectionName: "defaultFlow", …}
db: NativeConnection {base: Mongoose, collections: {…}, models: {…}, config: {…}, replica: false, …}
discriminators: undefined
events: EventEmitter {_events: {…}, _eventsCount: 0, _maxListeners: undefined}
hooks: Kareem {_pres: Map(8), _posts: Map(2)}
model: ƒ model(name)
modelName: "DefaultFlow"
paginate: ƒ paginate(query, options, callback)
schema: Schema {obj: {…}, paths: {…}, aliases: {…}, subpaths: {…}, virtuals: {…}, …}
Symbol(mongoose#Model): true
_middleware: Kareem {_pres: Map(7), _posts: Map(2)}
arguments: (...)
caller: (...)
length: 3
name: "model"
prototype: Model {db: NativeConnection, discriminators: undefined, …}
__proto__: ƒ Model(doc, fields, skipId)
[[FunctionLocation]]: model.js:4386
[[Scopes]]: Scopes[2]
Message: ƒ model(doc, fields, skipId)
Process: ƒ model(doc, fields, skipId)
Task: ƒ model(doc, fields, skipId)
Workflow: ƒ model(doc, fields, skipId)

}
```

JSON.stringify() not support it

**Comment by PaquitoSoft** [comment]
Again, I'm not sure what you're trying to achieve, but if you want to store a result from a database query, I guess you should use this Mongoose methods:
- [toObject](https://mongoosejs.com/docs/api/document.html#document_Document-toObject)
- [toJSON](https://mongoosejs.com/docs/api/document.html#document_Document-toJSON)

**Comment by RezaErfani67** [comment]
in my application, users make and delete its own collection and filds...
i want to collect all mongoose model in one variable...
before i go on cluster every thing was good...

```javascript
//model.js ==>
module.exports={


        DefaultFlow: require('./shared/defaultFlow/defaultFlow'),
         DefaultFlowChild: require('./shared/defaultFlow/defaultFlowChild'),
        User: require('./auth/user'),
         Task: require('./shared/Task/task'),
....
}

//in index.js==>
let model=require('./model);
model['Task'].findOne()...
model['User'].findOne()
```
i could change the model and push it any other model....
model[dynaCollection]=mongoose.model('dynaCollection');
but after i go on cluster... :(
i force to store all my models in sharing memory ...
because all core of cpu should know about the models of application...
unfortunately i cant do this and cant find any module to serialize model.js

**Comment by RezaErfani67** [comment]
can you please help me
